version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next:
        patterns:
          - next
          - "@next/*"
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
      playwright:
        patterns:
          - playwright
          - "@playwright/test"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
